### ISSUE TITLE
OutOfMemory exception in Docker under Ubuntu 18.4

### ISSUE THREAD

**Issue by PaulParau** [microsoft/Microsoft.IO.RecyclableMemoryStream#230]
Hello, I have encountered an interesting issue when using `RecyclableMemoryStreamManager` and I'd like to get some more insight.

Environment:
- .NET6 application, 64 bit
- 3GB max memory
- Ubuntu 18.4 image, under Docker also running through Ubuntu 18.4

Scenario: a large number of streams (30 000 - 50 000) are retrieved through `RecyclableMemoryStreamManager.GetStream(tag, capacity)`, with requested capacities and number of bytes written being generally small (a few hundred bytes). The `RecyclableMemoryStreamManager` is configured with a default block size of 131 072.

Issue: in the specific environment described above our application always crashes with an OutOfMemory exception. In any other environment we've tested (running under Windows 10 or under an Ubuntu 18.4 image but with Docker running through another Linux distro) we were unable to reproduce it, and memory consumption never appears to reach the limit (it stays around 300-500 MB). The issue is fixed if we configure the block size to be smaller (1024) or if we simply allocate a `new MemoryStream(capacity)` instead of doing `GetStream(tag, capacity)`.

While I understand that the default block size we were using creates the potential for a large memory consumption, the streams are short lived and memory consumption stays fairly low on all environments we've tested except one.

Does anybody have any insight into why this might be happening? Is it a potential bug in the library, or is it more likely something related to Docker/Ubuntu?

**Comment by benmwatson** [comment]
What is the message and stack of the `OutOfMemoryException`? In RMS, OOM is used to indicate that the desired allocation couldn't happen for a number of different reasons (please search through the code for the few occurrences).

More generally in .NET, OOM is used for all sorts of similar or related situations. The array was too big, or memory couldn't be allocated in a specific location (I saw this once when looking at jitting issues many years ago). I find that these days it's almost never because you're running out of physical memory. It's some other memory-related limit you're running into.

**Comment by PaulParau** [comment]
Hi, here's the stack:

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
   at Microsoft.IO.RecyclableMemoryStreamManager.GetBlock() in /_/src/RecyclableMemoryStreamManager.cs:line 377
   at Microsoft.IO.RecyclableMemoryStream.EnsureCapacity(Int64 newCapacity) in /_/src/RecyclableMemoryStream.cs:line 1561
   at Microsoft.IO.RecyclableMemoryStream..ctor(RecyclableMemoryStreamManager memoryManager, Guid id, String tag, Int64 requestedSize, Byte[] initialLargeBuffer) in /_/src/RecyclableMemoryStream.cs:line 277
   at Microsoft.IO.RecyclableMemoryStreamManager.GetStream(String tag, Int32 requiredSize) in /_/src/RecyclableMemoryStreamManager.cs:line 763
```

The capacity requested is not big at all (<100 bytes). When monitoring our application we can see that memory consumption slowly increases up until a few hundred MB and then it quickly grows to more than 2 GB and we start getting these Exceptions.

**Comment by robert-mynio** [comment]
One thing to mention is that once the OutOfMemory is thrown, the memory is not released anymore and we have a high memory usage for the kubernetes pod on which the Docker container runs. The only workaround we have right now is to call Environment.FailFast() when catching the OOM exception.

**Comment by benmwatson** [comment]
The line numbers don't match up perfectly with the latest code (are you using the latest version), but I think it's close enough. It's allocating a new block (so whatever size `BlockSize` is set at).

My suspicion is that there is something else going wrong in the process and this stack is just a side-effect. Perhaps streams are not always being disposed, they're being held onto, and memory is fundamentally leaking. Or something completely unrelated to RMS is leaking all of your memory. Your memory might be higher than you think, and in the image with more constraints, you're hitting the limits earlier. 

It doesn't look like a problem fundamentally with the library.

**Comment by PaulParau** [comment]
The strange thing is that it's only happening on a specific environment. I understand that we can have memory leaks, or an exaggerated consumption but I would expect the behavior to be more or less the same on different platforms.

**Comment by benmwatson** [comment]
Closing because I don't see anything actionable here.
